FROM garlictech2/workflows-angular:v15.0.0
ENV NO_UPDATE_NOTIFIER 1

# install_dependencies will merge deps in the container
COPY ./package.json /app/package.project.json
ADD src /app/src

RUN scripts/install_dependencies.js
