FROM garlictech2/angular2-webapp:v2.4.7

ARG NPM_TOKEN

RUN mkdir -p /app/src/subrepos /app/src/assets

COPY src/subrepos /app/src/subrepos/
COPY package.json /app/package.project.json

RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc && \
  scripts/install_dependencies
