version: '2'

services:
  deepstream:
    image: docker.garlictech.com/gtrack-deepstream-staging
    ports:
      - 6020:6020
    env_file:
      - ./service.env
      - ./tokens.env
    environment:
      - RETHINKDB_USER=admin
      - RETHINKDB_PASSWORD=''
    depends_on:
      - rethinkdb
      - redis
    restart: always

  redis:
    image: redis:alpine

  rethinkdb:
    image: rethinkdb
    ports:
      - "28016:28016"
      - "8091:8080"
  deepstream_providers:
    image: docker.garlictech.com/gtrack-deepstream-providers-staging
    env_file:
      - ./service.env
      - ./tokens.env
    depends_on:
      - deepstream
    restart: always
