version: '3.1'

services:
  gtrack-admin-site.universal-server:
    build:
      context: ..
      dockerfile: Dockerfile.universal
    environment:
      - NODE_ENV
      - CI
    command: 'npm run server:universal'
