version: '3.1'

services:
  garlictech.gtrack-admin-site.prod:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV
      - CI
    ports:
      - '9081:80'
    depends_on:
      - deepstream_providers
