version: '3.1'

services:
  garlictech.gtrack-admin-site.e2e-tester:
    build:
      context: "../e2e"
    volumes:
      - "../e2e/src:/protractor/src"
      - "../e2e/dist:/protractor/dist"
      - "../reports/e2e:/protractor/reports"
      - "/dev/shm:/dev/shm"
    privileged: true
    network_mode: "host"
