version: '3.1'

services:
  deepstream:
    image: docker.garlictech.com/gtrack-deepstream-staging:latest
    env_file:
      - ./service.env
      - ./tokens.env
    environment:
      - RETHINKDB_USER=admin
    depends_on:
      - rethinkdb
      - redis
    restart: always
    secrets:
      - DEEPSTREAM_PROVIDER_JWT_SECRET

  redis:
    image: redis:alpine

  rethinkdb:
    image: rethinkdb
    env_file:
      - './service.env'
    command: ['sh', '-c', 'rethinkdb --bind all --initial-password $${RETHINKDB_PASSWORD}']

  deepstream_providers:
    image: docker.garlictech.com/gtrack-deepstream-providers-staging
    env_file:
      - ./service.env
      - ./tokens.env
    depends_on:
      - deepstream
    restart: always
    secrets:
      - DEEPSTREAM_PROVIDER_JWT_SECRET
      - RETHINKDB_PASSWORD

secrets:
  DEEPSTREAM_PROVIDER_JWT_SECRET:
    file: secrets/DEEPSTREAM_PROVIDER_JWT_SECRET.secret.txt
  DEEPSTREAM_USER_JWT_SECRET:
    file: secrets/DEEPSTREAM_USER_JWT_SECRET.secret.txt
  RETHINKDB_PASSWORD:
    file: secrets/RETHINKDB_PASSWORD.secret.txt
