version: '3.1'

services:
  gtrack-admin-site.webpack-server:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: $NPM_TOKEN_Garlictech
    volumes:
      - '../src:/app/src'
      - '../artifacts:/app/artifacts'
      - './hooks:/app/hooks'
      - '../angular.json:/app/angular.json'
    environment:
      - NODE_ENV
      - CI
      - PROJECT_CONFIG
    entrypoint: ['sh', '-c', '${DOCKER_CMD}']
