version: '2'

services:
  deepstream:
    image: docker.garlictech.com/deepstream-gtrack:0.2.1
    ports:
      - 6020:6020
    env_file:
      - ./service.env
      - ./tokens.env
    depends_on:
      - rethinkdb
      - redis
    restart: always

  redis:
    image: redis:alpine

  rethinkdb:
    image: rethinkdb

  deepstream_providers:
    image: docker.garlictech.com/gtrack-providers:latest
    env_file:
      - ./service.env
      - ./tokens.env
    depends_on:
      - deepstream
    restart: always
