#!/usr/bin/env bash
set -e
. .env

npm run travis before_install

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  docker/login.sh
fi

if [ -f hooks/travis/before_install_project ]; then
  hooks/travis/before_install_project
fi
