#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
npm run travis script

# ADD YOUR PARTS HERE
npm run build
npm run lint
npm run unittest

if [[ "$BUILD_TYPE" == "aot" ]]; then
  npm run build:debug:aot
else
  npm run build:prod:debug
fi

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  npm run e2e:prod
fi
