#!/usr/bin/env bash
set -e

# DO NOT REMOVE THIS SECTION UNLESS YOU KNOW WHAT YOU DO
npm run travis script

# ADD YOUR PARTS HERE
npm run build
#npm run lint
npm run unittest
npm run build:prod:debug

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  npm run e2e:prod
fi

if [ -f hooks/travis/script_project ]; then
  hooks/travis/script_project
fi

