import { EColorCodes } from './color-codes';

export const DEFAULT_COLOR_MAP = {
  asterisco: EColorCodes.LIGHT_GREEN,
  atm: EColorCodes.BLUE,
  bank: EColorCodes.BLUE,
  bicycle_parking: EColorCodes.BROWN,
  bicycle: EColorCodes.CYAN,
  bus_station: EColorCodes.BROWN,
  cafe: EColorCodes.PURPLE,
  cave_entrance: EColorCodes.LIGHT_GREEN,
  checkpoint: EColorCodes.DARK_MAGENTA,
  city: EColorCodes.LIGHT_GREEN,
  cliff: EColorCodes.DARK_GREEN,
  drinking_water: EColorCodes.DARK_GREEN,
  finish: EColorCodes.ORANGE,
  fuel: EColorCodes.BROWN,
  hiking: EColorCodes.ORANGE,
  hunting_stand: EColorCodes.ORANGE,
  lodging: EColorCodes.PURPLE,
  marketplace: EColorCodes.DARK_GREEN,
  mud: EColorCodes.DARK_GREEN,
  parking: EColorCodes.BROWN,
  peak: EColorCodes.DARK_GREEN,
  pharmacy: EColorCodes.RED,
  photo: EColorCodes.GREY,
  picnic: EColorCodes.LIGHT_GREEN,
  place_of_worship: EColorCodes.LIGHT_GREEN,
  police: EColorCodes.BLUE,
  post_box: EColorCodes.BLUE,
  post_office: EColorCodes.BLUE,
  pub: EColorCodes.PURPLE,
  recycling: EColorCodes.DARK_GREEN,
  restaurant: EColorCodes.PURPLE,
  shelter: EColorCodes.LIGHT_GREEN,
  sight: EColorCodes.LIGHT_GREEN,
  spring: EColorCodes.DARK_GREEN,
  start: EColorCodes.ORANGE,
  start_finish: EColorCodes.ORANGE,
  store: EColorCodes.CYAN,
  sunsetland: EColorCodes.DARK_GREEN,
  telephone: EColorCodes.BLUE,
  toilets: EColorCodes.RED,
  train_station: EColorCodes.BROWN,
  tree: EColorCodes.DARK_GREEN,
  waste_basket: EColorCodes.BLUE,
  water: EColorCodes.DARK_GREEN
};
