#!/usr/bin/env bash
set -e
. .env

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  openssl aes-256-cbc -K $encrypted_400bd271cf1b_key -iv $encrypted_400bd271cf1b_iv -in secrets.tgz.enc -out secrets.tgz -d
  tar -zxvf secrets.tgz
fi
