#!/usr/bin/env bash
set -e

if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
  pip install --user awscli
  docker/login.sh
  openssl aes-256-cbc -K $encrypted_400bd271cf1b_key -iv $encrypted_400bd271cf1b_iv -in secrets.tgz.enc -out secrets.tgz -d
  tar -zxvf secrets.tgz
fi

npm run travis before_install
